///
/// @Generated by Mockolo
///

import Combine
import Foundation
import Model

public class GithubUseCaseProtocolMock: GithubUseCaseProtocol {
    public init() { }

    public private(set) var searchCallCount = 0
    public var searchHandler: ((String) -> (AnyPublisher<[GitHubRepository], APIError>))?
    public func search(keyword: String) -> AnyPublisher<[GitHubRepository], APIError> {
        searchCallCount += 1
        if let searchHandler = searchHandler {
            return searchHandler(keyword)
        }
        fatalError("searchHandler returns can't have a default value thus its handler must be set")
    }
}
